version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure:3

  web:
    build: .
    command: sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure:3
    depends_on:
      - db
      - redis

  redis:
    image: redis

  celery:
    build: .
    command: celery -A plyart_project worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    restart: on-failure:3
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A plyart_project beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    restart: on-failure:3
    depends_on:
      - redis