# Generated by Django 4.0.3 on 2022-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включить/Выключить'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(default='#', max_length=300, verbose_name='Ссылка на продук'),
        ),
    ]
