# Generated by Django 4.0.3 on 2022-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_slider_options_alter_slider_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='background',
            field=models.ImageField(default=1, upload_to='slides', verbose_name='Задний фон'),
            preserve_default=False,
        ),
    ]
