# Generated by Django 4.0.3 on 2022-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_slider_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('phone_number2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона (Не обязательно)')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_from', models.CharField(max_length=255, verbose_name='Часы работы с')),
                ('work_to', models.CharField(max_length=255, verbose_name='Часы работы по')),
            ],
        ),
    ]
