# Generated by Django 4.0.3 on 2022-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/no_image.png', upload_to='products/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
